### PR TITLE
vsresize: add support for field-based and interlaced video

### LINKED ISSUE #216: Resizers don't like interlaced video
Even operations like bit depth conversion fail with an error if the input has the _FieldBased property and it's not 0.

### PR DESCRIPTION
**Pull request by sekrit-twc**
Fixes #216

### CODE REVIEW

File: src/core/vsresize.cpp [hunk 1]
```diff
@@ -503,10 +533,24 @@ namespace {
...
+        void init_pack(const vszimgxx::FilterGraph &graph, VSFrameRef *frame, const zimg_image_format &format, bool interlaced,
+                       const VSFormat *vsformat, VSCore *core, const VSAPI *vsapi) {
             init_common(graph, true, format, vsformat, core, vsapi);
             import_frame_as_buffer(frame, &m_plane_buf.m, ZIMG_BUFFER_MAX, vsapi);
 
+            if (interlaced) {
+                unsigned order = format.field_parity == ZIMG_FIELD_BOTTOM ? 1 : 0;
+
+                // CompatBGR32 is upside-down.
+                if (vsformat->colorFamily == cmCompat)
```
Comment (dubhater) [inline src/core/vsresize.cpp]: This will assume YUY2 is upside down too, right?

Comment (sekrit-twc) [inline src/core/vsresize.cpp]: It's a bug
